spring.application.name=FullStackWebApp

spring.datasource.url=jdbc:mysql://localhost:3306/fullstack
spring.datasource.username=${username}
spring.datasource.password=${password}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=nR6Y3JjY0R6Z0F5bU5aR1R0dXlYVjFzS0hPb3h6T0N4b1B4T1ZkRkZKc3dQdQ==

spring.jpa.differ-datasource-initialization=true